name: GitHub Actions
on: [push]
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cd ${{ github.workspace }}
      - run: pip3 install -r requirements.txt
      - run: python -m compileall -q .
      - run: python3 tests.py
      - run: echo "🍏 This job's status is ${{ job.status }}."
